# SPDX-FileCopyrightText: 2023 - 2025 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- name: Ensure PrivateBin path exists
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: 0750
    owner: "{{ privatebin_uid }}"
    group: "{{ privatebin_gid }}"
  with_items:
    - "{{ privatebin_base_path }}"

- name: Ensure PrivateBin support files installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/{{ item }}.j2"
    dest: "{{ privatebin_base_path }}/{{ item }}"
    mode: 0640
    owner: "{{ privatebin_uid }}"
    group: "{{ privatebin_gid }}"
  with_items:
    - env
    - labels

- name: Ensure PrivateBin config file installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/config.sample.php.j2"
    dest: "{{ privatebin_base_path }}/config.php"
    mode: 0640
    owner: "{{ privatebin_uid }}"
    group: "{{ privatebin_gid }}"

- name: Ensure PrivateBin container image is pulled
  community.docker.docker_image:
    name: "{{ privatebin_container_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"
    force_source: "{{ privatebin_container_image_force_pull if ansible_version.major > 2 or ansible_version.minor >= 8 else omit }}"
    force: "{{ omit if ansible_version.major > 2 or ansible_version.minor >= 8 else privatebin_container_image_force_pull }}"

- name: Ensure PrivateBin container network is created
  community.general.docker_network:
    enable_ipv6: "{{ devture_systemd_docker_base_ipv6_enabled }}"
    name: "{{ privatebin_container_network }}"
    driver: bridge
    driver_options: "{{ devture_systemd_docker_base_container_networks_driver_options }}"

- name: Ensure PrivateBin systemd service is present
  ansible.builtin.template:
    src: "{{ role_path }}/templates/systemd/privatebin.service.j2"
    dest: "{{ devture_systemd_docker_base_systemd_path }}/{{ privatebin_identifier }}.service"
    mode: 0644
