# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Perform PrivateBin installation tasks
  when: privatebin_enabled | bool
  tags:
    - setup-all
    - setup-privatebin
    - install-all
    - install-privatebin
  block:
    - name: Validate PrivateBin configuration
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"
    - name: Install PrivateBin
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- name: Perform PrivateBin uninstallation tasks
  when: not privatebin_enabled | bool
  tags:
    - setup-all
    - setup-privatebin
  block:
    - name: Uninstall PrivateBin
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
